version: "3.8"
services:
  thtracker_api:
    build:
      context: .
      dockerfile: Dockerfile
    image: thtracker-api:local
    ports:
      - "80:80"
    env_file: .env
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
